#include <boost/python/module.hpp>
#include <boost/python/def.hpp>
#include "constants.h"

BOOST_PYTHON_MODULE(constants)
{
    using namespace boost::python;

    scope().attr("TILEDB_VERSION") = TILEDB_VERSION;

	scope().attr("TILEDB_OK") = TILEDB_OK;
	scope().attr("TILEDB_ERR") = TILEDB_ERR;

	scope().attr("TILEDB_ARRAY_READ") = TILEDB_ARRAY_READ;
	scope().attr("TILEDB_ARRAY_WRITE") = TILEDB_ARRAY_WRITE;
	scope().attr("TILEDB_ARRAY_WRITE_UNSORTED") = TILEDB_ARRAY_WRITE_UNSORTED;
	    
	scope().attr("TILEDB_METADATA_READ") = TILEDB_METADATA_READ;
	scope().attr("TILEDB_METADATA_WRITE") = TILEDB_METADATA_WRITE;

	scope().attr("TILEDB_WORKSPACE") = TILEDB_WORKSPACE;
	scope().attr("TILEDB_GROUP") = TILEDB_GROUP;
	scope().attr("TILEDB_ARRAY") = TILEDB_ARRAY;
	scope().attr("TILEDB_METADATA") = TILEDB_METADATA;

	scope().attr("TILEDB_IO_MMAP") = TILEDB_IO_MMAP;
	scope().attr("TILEDB_IO_READ") = TILEDB_IO_READ;
	scope().attr("TILEDB_IO_MPI") = TILEDB_IO_MPI;
	scope().attr("TILEDB_IO_WRITE") = TILEDB_IO_WRITE;

	scope().attr("TILEDB_AIO_ERR") = TILEDB_AIO_ERR;
	scope().attr("TILEDB_AIO_COMPLETED") = TILEDB_AIO_COMPLETED;
	scope().attr("TILEDB_AIO_INPROGRESS") = TILEDB_AIO_INPROGRESS;
	scope().attr("TILEDB_AIO_OVERFLOW") = TILEDB_AIO_OVERFLOW;

	scope().attr("TILEDB_NAME_MAX_LEN") = TILEDB_NAME_MAX_LEN;

	scope().attr("TILEDB_CONSOLIDATION_BUFFER_SIZE") = TILEDB_CONSOLIDATION_BUFFER_SIZE;

	scope().attr("TILEDB_EMPTY_INT32") = TILEDB_EMPTY_INT32;
	scope().attr("TILEDB_EMPTY_INT64") = TILEDB_EMPTY_INT64;
	scope().attr("TILEDB_EMPTY_FLOAT32") = TILEDB_EMPTY_FLOAT32;
	scope().attr("TILEDB_EMPTY_FLOAT64") = TILEDB_EMPTY_FLOAT64;
	scope().attr("TILEDB_EMPTY_CHAR") = TILEDB_EMPTY_CHAR;

	scope().attr("TILEDB_VAR_NUM") = TILEDB_VAR_NUM;
	scope().attr("TILEDB_VAR_SIZE") = TILEDB_VAR_SIZE;

	scope().attr("TILEDB_INT32") = TILEDB_INT32;
	scope().attr("TILEDB_INT64") = TILEDB_INT64;
	scope().attr("TILEDB_FLOAT32") = TILEDB_FLOAT32;
	scope().attr("TILEDB_FLOAT64") = TILEDB_FLOAT64;
	scope().attr("TILEDB_CHAR") = TILEDB_CHAR;

	scope().attr("TILEDB_ROW_MAJOR") = TILEDB_ROW_MAJOR;
	scope().attr("TILEDB_COL_MAJOR") = TILEDB_COL_MAJOR;
	scope().attr("TILEDB_HILBERT") = TILEDB_HILBERT;

	scope().attr("TILEDB_NO_COMPRESSION") = TILEDB_NO_COMPRESSION;
	scope().attr("TILEDB_GZIP") = TILEDB_GZIP;

	scope().attr("TILEDB_COORDS") = TILEDB_COORDS;
	scope().attr("TILEDB_KEY") = TILEDB_KEY;

	scope().attr("TILEDB_FILE_SUFFIX") = TILEDB_FILE_SUFFIX;
	scope().attr("TILEDB_GZIP_SUFFIX") = TILEDB_GZIP_SUFFIX;

	scope().attr("TILEDB_GZIP_CHUNK_SIZE") = TILEDB_GZIP_CHUNK_SIZE;

	scope().attr("TILEDB_ARRAY_SCHEMA_FILENAME") = TILEDB_ARRAY_SCHEMA_FILENAME;
	scope().attr("TILEDB_METADATA_SCHEMA_FILENAME") = TILEDB_METADATA_SCHEMA_FILENAME;
	scope().attr("TILEDB_BOOK_KEEPING_FILENAME") = TILEDB_BOOK_KEEPING_FILENAME;
	scope().attr("TILEDB_FRAGMENT_FILENAME") = TILEDB_FRAGMENT_FILENAME;
	scope().attr("TILEDB_GROUP_FILENAME") = TILEDB_GROUP_FILENAME;
	scope().attr("TILEDB_WORKSPACE_FILENAME") = TILEDB_WORKSPACE_FILENAME;

	scope().attr("TILEDB_SORTED_BUFFER_SIZE") = TILEDB_SORTED_BUFFER_SIZE;
	scope().attr("TILEDB_SORTED_BUFFER_VAR_SIZE") = TILEDB_SORTED_BUFFER_VAR_SIZE;
}
